import { pgTable, text, serial, integer, boolean, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { relations } from "drizzle-orm";

// === TABLE DEFINITIONS ===

export const users = pgTable("users", {
  id: text("id").primaryKey(), // We'll generate a UUID on the client/server for the session
  avatarSeed: text("avatar_seed").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const recordings = pgTable("recordings", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id),
  audioUrl: text("audio_url").notNull(),
  duration: integer("duration").notNull(), // in seconds
  mood: text("mood").notNull(), // 'Happy', 'Sad', etc.
  likesCount: integer("likes_count").default(0).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const likes = pgTable("likes", {
  id: serial("id").primaryKey(),
  recordingId: integer("recording_id").notNull().references(() => recordings.id),
  userId: text("user_id").notNull().references(() => users.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// === RELATIONS ===

export const usersRelations = relations(users, ({ many }) => ({
  recordings: many(recordings),
  likes: many(likes),
}));

export const recordingsRelations = relations(recordings, ({ one, many }) => ({
  user: one(users, {
    fields: [recordings.userId],
    references: [users.id],
  }),
  likes: many(likes),
}));

export const likesRelations = relations(likes, ({ one }) => ({
  recording: one(recordings, {
    fields: [likes.recordingId],
    references: [recordings.id],
  }),
  user: one(users, {
    fields: [likes.userId],
    references: [users.id],
  }),
}));

// === BASE SCHEMAS ===

export const insertUserSchema = createInsertSchema(users);
export const insertRecordingSchema = createInsertSchema(recordings).omit({ 
  id: true, 
  likesCount: true, 
  createdAt: true 
});
export const insertLikeSchema = createInsertSchema(likes).omit({
  id: true,
  createdAt: true
});

// === EXPLICIT API CONTRACT TYPES ===

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export type Recording = typeof recordings.$inferSelect;
export type InsertRecording = z.infer<typeof insertRecordingSchema>;

export type Like = typeof likes.$inferSelect;
export type InsertLike = z.infer<typeof insertLikeSchema>;

// Request Types
export type CreateUserRequest = {
  avatarSeed?: string; // Optional, can be generated by server
};

export type CreateRecordingRequest = InsertRecording;

export type CreateLikeRequest = {
  userId: string;
};

// Response Types
export type UserResponse = User;
export type RecordingResponse = Recording & {
  user?: User;
  isLiked?: boolean; // If a userId is provided in query
};
export type RecordingsListResponse = RecordingResponse[];
